export const GET_QUESTIONS = 'GET_QUESTIONS';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const PREVIOUS_QUESTION = 'PREVIOUS_QUESTION';
export const RESET_QUESTIONS = 'RESET_QUESTIONS';
export const OFFLINE_QUESTIONS = 'OFFLINE_QUESTIONS';
export const ANSWER_QUESTION = 'ANSWER_QUESTION';
export const RESET_ANSWERS = 'RESET_ANSWERS';
